= Signal Numérique
:hardbreaks-option:
:toc:

== C'est quoi un signal numérique
Un signal numérique est un signal discret (à la différence d'un signal analogique, qui est continue) d'une , c'est à dire qu'il ne peut prendre qu'un nombre fini de valeur.
Dans le cas d'un circuit numérique, ces valeurs sont binaires (0 ou 1).
Il est possible que le signal numérique soit le résultat d'un échantillonnage d'un autre signal.



=== Avantage
Le signal numérique a plusieurs avantages:

. Facilité de traitement + 
Principal avantage des signal numérique, le traitement de ce signal est simple par rapport à un signal analogique:
.. Tous les signaux échantillonnés pourront être manipulés de la même manière, qu'importe la source du signal échantillonné (audio, vidéo, tension...)
.. Ils peuvent être traités à l'aide d'ordinateurs et d'autres dispositifs électroniques.
.. Puisque ces signaux sont de par leur nature mathématique, on peut les modifier et manipuler pour effectuer diverses opérations, telles que la compression, le filtrage, la modélisation etc.
. Les signaux numériques peuvent être stockés facilement.
. Très bonne résistance aux variations, que cela soit les interférences ou les perturbations. 

Ces avantages permettent aux signaux numériques d'être transmis sur de longues distances sans craindre de perte significative de qualité. De plus, leur nature de signaux mathématique facilite leur traitement ainsi que leur stockage : si un signal analogique nécessite des filtres (RC, RLC...) spécifique pour être traités, les signaux numériques peuvent être traité de la même manière, mais avec l'unique aide d'un ordinateur.

=== Inconvenant
Le signal numérique ne propose pas que des avantages, mais aussi des inconvenants:

. Qualité inférieure à celle d'un signal analogique
. La bande passante nécessaire



== Conversion Analogique / Numérique (CAN)

=== 1) L'échantillonnage
L'échantillonnage consiste à enregistrer, à intervalle de temps régulier, la valeur d'un signal.

La fréquence d'échantillonnage du signal doit cependant être supérieure à deux fois la fréquence du signal échantillonné sinon l'échantillonnage perdra en précision (*Critère de Shannon*).
Plus la fréquence d'échantillonnage est grande, plus le signal résultant de l'échantillonnage sera précis, mais plus le nombre de valeur échantillonné sera grand, et donc plus le fichier sera lourd.

=== 2) La Quantification
La quantification est la seconde étape nécessaire à la numérisation d'un signal analogique. 
Après avoir réalisé l'échantillonnage, on va "arrondir" les valeurs obtenues afin d'approcher un signal continu par un certains nombres de valeurs définies.
Par exemple, si une valeur est comprise 7,5 et 8,5, alors on pourra l'arrondir à 8.

Comme pour l'échantillonnage, on peut améliorer la précision du signal en augmentant la précision de l'arrondit.

=== 3) La représentation numérique
Une fois la quantification réalisée, il faut convertir ce signal en séquence binaire (0 ou 1) pour permettre son traitement par la suite.

=== 4) Stockage et traitement
Finalement, une fois le signal converti en une suite binaire, on peut alors le stocker dans la mémoire d'un dispositif numérique pour qu'il soit traité (logiciel de mixage), exploité (FFT) ou encore pour être converti en un signal analogique (exemple, un CD).




= Sauce
:hide-uri-scheme:

. https://www.lelivrescolaire.fr/page/7359612
. http://ressources.uac.bj/ressources/unt/iutenligne/sciences-de-l-ingenieur/791-module-signaux-systeme/AnalogiqueNumerique/index.html
. https://en.wikipedia.org/wiki/Digital_signal
. https://en.wikipedia.org/wiki/Digital_signal_processing
. 
. 
. 
. 
. 
. 